UPDATE maintenance_locations
SET label = CONCAT('Quarto ', TRIM(code)),
    description = CONCAT('Quarto do piso ', floor, '.'),
    updated_by = 'system.catalog.pt'
WHERE location_type = 'ROOM'
  AND location_category = 'APARTMENT'
  AND TRIM(code) REGEXP '^[0-9]{3}$';

UPDATE maintenance_locations
SET label = CASE TRIM(code)
        WHEN '100' THEN 'Areas comuns piso 1'
        WHEN '200' THEN 'Areas comuns piso 2'
        WHEN '300' THEN 'Areas comuns piso 3'
        WHEN '400' THEN 'Areas comuns piso 4'
        WHEN '500' THEN 'Recepcao'
        WHEN '501' THEN 'Reservas'
        WHEN '502' THEN 'Sala business'
        WHEN '503' THEN 'Elevador'
        WHEN '504' THEN 'Sala de TV'
        WHEN '505' THEN 'Deposito de eventos'
        WHEN '506' THEN 'Sala de jogos'
        WHEN '507' THEN 'Rouparia central'
        WHEN '508' THEN 'Governanca'
        WHEN '509' THEN 'Escritorios RH-Financeiro'
        WHEN '510' THEN 'Elevador de servico'
        WHEN '511' THEN 'Almoxarifado'
        WHEN '512' THEN 'Cozinha'
        WHEN '513' THEN 'Restaurante'
        WHEN '514' THEN 'Piscina'
        WHEN '515' THEN 'Piscina aquecida'
        WHEN '516' THEN 'Academia'
        WHEN '517' THEN 'Spa'
        WHEN '518' THEN 'Sauna'
        WHEN '519' THEN 'Recreacao'
        WHEN '520' THEN 'Estacionamento'
        WHEN '521' THEN 'Entrada do hotel'
        WHEN '522' THEN 'Caldeira'
        WHEN '523' THEN 'Reservatorio'
        WHEN '524' THEN 'Central eletrica'
        WHEN '525' THEN 'Cameras'
        WHEN '526' THEN 'Praia'
        WHEN '527' THEN 'Jacuzzi'
        WHEN '528' THEN 'Refeitorio'
        ELSE label
    END,
    description = CASE TRIM(code)
        WHEN '100' THEN 'Corredores e areas comuns do primeiro piso.'
        WHEN '200' THEN 'Corredores e areas comuns do segundo piso.'
        WHEN '300' THEN 'Corredores e areas comuns do terceiro piso.'
        WHEN '400' THEN 'Corredores e areas comuns do quarto piso.'
        WHEN '500' THEN 'Area de recepcao do hotel.'
        WHEN '501' THEN 'Area administrativa de reservas.'
        WHEN '502' THEN 'Sala business do hotel.'
        WHEN '503' THEN 'Elevador principal do hotel.'
        WHEN '504' THEN 'Sala de TV para hospedes.'
        WHEN '505' THEN 'Deposito de eventos.'
        WHEN '506' THEN 'Sala de jogos e recreacao.'
        WHEN '507' THEN 'Rouparia central do hotel.'
        WHEN '508' THEN 'Area de governanca.'
        WHEN '509' THEN 'Escritorios administrativos de RH e financeiro.'
        WHEN '510' THEN 'Elevador de servico.'
        WHEN '511' THEN 'Almoxarifado e deposito geral.'
        WHEN '512' THEN 'Cozinha principal.'
        WHEN '513' THEN 'Area do restaurante.'
        WHEN '514' THEN 'Piscina externa.'
        WHEN '515' THEN 'Piscina aquecida.'
        WHEN '516' THEN 'Academia do hotel.'
        WHEN '517' THEN 'Area de spa.'
        WHEN '518' THEN 'Area de sauna.'
        WHEN '519' THEN 'Area de recreacao.'
        WHEN '520' THEN 'Estacionamento do hotel.'
        WHEN '521' THEN 'Entrada principal do hotel.'
        WHEN '522' THEN 'Sala de caldeira.'
        WHEN '523' THEN 'Reservatorio do hotel.'
        WHEN '524' THEN 'Central eletrica.'
        WHEN '525' THEN 'Sistema de cameras.'
        WHEN '526' THEN 'Area de praia.'
        WHEN '527' THEN 'Area de jacuzzi.'
        WHEN '528' THEN 'Refeitorio.'
        ELSE description
    END,
    updated_by = 'system.catalog.pt'
WHERE location_type = 'COMMON_AREA'
  AND TRIM(code) REGEXP '^[0-9]{3}$';

UPDATE maintenance_locations
SET label = CONCAT('Chale ', LPAD(TRIM(code), 2, '0')),
    description = CONCAT('Unidade de hospedagem chale ', LPAD(TRIM(code), 2, '0'), '.'),
    updated_by = 'system.catalog.pt'
WHERE location_type = 'ROOM'
  AND location_category = 'CHALET'
  AND TRIM(code) REGEXP '^[0-9]{2}$';

UPDATE maintenance_orders
SET location_label_snapshot = CASE
        WHEN location_type_snapshot = 'ROOM'
             AND location_category_snapshot = 'APARTMENT'
             AND TRIM(location_code_snapshot) REGEXP '^[0-9]{3}$'
            THEN CONCAT('Quarto ', TRIM(location_code_snapshot))
        WHEN location_type_snapshot = 'ROOM'
             AND location_category_snapshot = 'CHALET'
             AND TRIM(location_code_snapshot) REGEXP '^[0-9]{2}$'
            THEN CONCAT('Chale ', LPAD(TRIM(location_code_snapshot), 2, '0'))
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '100' THEN 'Areas comuns piso 1'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '200' THEN 'Areas comuns piso 2'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '300' THEN 'Areas comuns piso 3'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '400' THEN 'Areas comuns piso 4'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '500' THEN 'Recepcao'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '501' THEN 'Reservas'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '502' THEN 'Sala business'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '503' THEN 'Elevador'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '504' THEN 'Sala de TV'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '505' THEN 'Deposito de eventos'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '506' THEN 'Sala de jogos'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '507' THEN 'Rouparia central'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '508' THEN 'Governanca'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '509' THEN 'Escritorios RH-Financeiro'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '510' THEN 'Elevador de servico'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '511' THEN 'Almoxarifado'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '512' THEN 'Cozinha'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '513' THEN 'Restaurante'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '514' THEN 'Piscina'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '515' THEN 'Piscina aquecida'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '516' THEN 'Academia'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '517' THEN 'Spa'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '518' THEN 'Sauna'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '519' THEN 'Recreacao'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '520' THEN 'Estacionamento'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '521' THEN 'Entrada do hotel'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '522' THEN 'Caldeira'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '523' THEN 'Reservatorio'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '524' THEN 'Central eletrica'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '525' THEN 'Cameras'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '526' THEN 'Praia'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '527' THEN 'Jacuzzi'
        WHEN location_type_snapshot = 'COMMON_AREA'
             AND TRIM(location_code_snapshot) = '528' THEN 'Refeitorio'
        ELSE location_label_snapshot
    END;
